bilinear_coefficients:
  mu: 0.01                                 # Should be equal to mu_start

experimental_params:
  output_folder: Output/NSE2D/WithAllModifications
  vtk_base_name: VPINNS_NSE2D

model_run_params:
  max_iter: 250000                              # Max iterations
  NN_model:                                     # NN architecture
  - 2
  - 30
  - 30
  - 30
  - 3
  pressure_correction: True                    # Pressure Correction or not
  reduced_pressure: True                        # Reduced Pressure or not
  reduced_shape_func: 4                         # Reduced Shape Function for pressure
  boundary_loss_tau: 2.0                       # Boundary Loss Parameter (Tau) as mentioned in Paper
  num_quad_points: 90                          # Number of Quadrature Points for Loss Calculation
  num_bound_points: 150                         # Number of Boundary Points for Loss Calculation
  num_residual_points: 100                      # Number of Residual Points for Loss Calculation
  num_elements_x: 1                                     # Number of Cells in x-direction
  num_elements_y: 1                                     # Number of Cells in y-direction
  num_shape_functions_x: 8                      # Number of Shape Functions in x-direction
  num_shape_functions_y: 8                      # Number of Shape Functions in y-direction
  learning_rate: 0.001                          # Learning Rate
  exact_solution_vtk: data/FEM.00001.vtk        # Exact Solution VTK File
  

lr_scheduler:
  use_lr_scheduler: True                            # Use LR Scheduler or not
  decay_rate: 0.5                               # Decay Rate
  decay_steps: 5000                            # Decay Steps
  initial_lr: 0.001                              # Initial Learning Rate

mu_scheduler:
  use_mu_scheduler: True                       # Use RE Scheduler or not
  mu_scheduler_type: step                     # Type of RE Scheduler ( exponential, step)
  mu_start: 1                                   # mu Start
  mu_end: 0.01                                   # mu End (Final)
  mu_threshold_iter_percentage: 0.7             # After this iteration number, the RE will be hardcoded to re_end
  mu_step_size: 1000

model_save_params:
  save_model: true                              # Save model or not
  save_frequency: 10000                          # Save model after every save_frequency iterations
  save_name: NSE2D_Liddriven_Without_PC_100

mlflow_parameters:
  use_mlflow: true                                          # Use MLFlow or not
  mlflow_experiment_name: NSE_Liddriven_Var_PINNS   # Name of the experiment
  mlflow_run_prefix:  "Meeting_experiment"                # Prefix of the run



