bilinear_coefficients:
  eps: 0.01                                     # Diffusion Coefficient
  bx: 1.0                                       # Advection Coefficient in x-direction
  by: 0.0                                       # Advection Coefficient in y-direction
  c: 0                                          # Reaction Coefficient
  stab_param_tau: 0.21                          ## Global Stabilisation Parameter for SUPG
  boundary_loss_tau: 10.0                       # Boundary Loss Parameter (Tau) as mentioned in Paper

model_run_params:
  max_iter: 50000                              # Max iterations
  NN_model:                                     # NN architecture
  - 2
  - 5
  - 5
  - 5
  - 1
  var_form: "VarPINNs"                        # Accepted : VarPINNs, VarPINNs_SUPG
  boundary_loss_tau: 10.0                       # Boundary Loss Parameter (Tau) as mentioned in Paper
  num_quad_points: 10                          # Number of Quadrature Points for Loss Calculation
  num_bound_points: 80                         # Number of Boundary Points for Loss Calculation
  num_residual_points: 100                      # Number of Residual Points for Loss Calculation
  num_elements_x: 4                                     # Number of Cells in x-direction
  num_elements_y: 4                                     # Number of Cells in y-direction
  num_shape_functions_x: 5                     # Number of Shape Functions in x-direction
  num_shape_functions_y: 5                     # Number of Shape Functions in y-direction
  learning_rate: 0.001                          # Learning Rate

model_save_params:
  save_model: true                              # Save model or not
  save_frequency: 10000                          # Save model after every save_frequency iterations
  save_directory: Output/SingularlyPerturbed/1
  save_name: SingularlyPerturbed

mlflow_parameters:
  use_mlflow: true                                          # Use MLFlow or not
  mlflow_experiment_name: SingularlyPerturbed_Experiments   # Name of the experiment



